### ISSUE TITLE
Issues with Auto-Translation Using Strapi Translate DeepL Provider

### ISSUE THREAD

**Issue by hadiulofficial** [Fekide/strapi-plugin-translate#413]
Hi all,

I'm having trouble with the Strapi Translate plugin using DeepL. Instead of translating, it's copying the source language content directly into the target fields. My settings and API key are correct, but it’s not working as expected. Has anyone faced this issue or know how to fix it?

#### Plugins Used:
- [Strapi Translate Plugin](https://market.strapi.io/plugins/strapi-plugin-translate)
- [Strapi Translate DeepL Provider](https://www.npmjs.com/package/strapi-provider-translate-deepl)

**Comment by sargreal** [comment]
Dear @hadiulofficial,

There may be several things that cause this.

Can you please share your setup, so that we might reproduce your issue locally?
- strapi and plugin versions
- plugin configuration for the translate plugin
- the schema of the content-type you are translating
- Optionally it would be very helpful if you create a minimal strapi installation in a public repository that reliably reproduces the issue.


Additionally as a side note: Please use the issue templates that are provided, since these ask these questions already.

**Comment by hadiulofficial** [comment]
Thanks, issue solved! The problem was with my configuration
